---
title       : R Presentation Demo
subtitle    : Illustration for some basic uses in R presentation
author      : Yan
job         : St
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, quiz, bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Bullets for presentations
This page includes som functions to show the content in data sets.
- Use the library function

```r
library(caret)
```
- Use the data function

```r
data(cars)
```
- Use summury function

```{r, echo=TRUE}
summary(cars)[1]
```

---



## Mathjax
-  $\LaTeX$ math formatting can be included
- The multivariate Gaussian pdf is:

$$f_Y(x)=\frac{1}{\sqrt{(2\pi)^n|\boldsymbol\Sigma|}}
\exp\left(-\frac{1}{2}({x}-{m})^T{\boldsymbol\Sigma}^{-1}({x}-{m})
\right)$$

- We can use the lm function to do multivariate regression by
```{r, eval=FALSE}
data(iris)
lm(Species ~ Sepal.Length + Sepal.Width, data=iris)
```

---

## Model Training
```{r, eval=TRUE}
library(ggplot2);library(rpart)
library(lattice);library(caret)
data(iris)
modFit <- train(Species ~ .,method="rpart",data=iris)
print(modFit$finalModel)
```

---

## Figure
```{r, echo=FALSE, eval=TRUE}
library(rattle)
library(ggplot2);library(rpart)
library(lattice);library(caret)
data(iris)
modFit <- train(Species ~ .,method="rpart",data=iris)
fancyRpartPlot(modFit$finalModel)
```
